# Robotics Radar - Frontier AI Research Configuration
# High-value sources for cutting-edge AI research and robotics breakthroughs

feeds:
  # 🧠 FRONTIER AI RESEARCH (WORKING)
  # arXiv Research Feeds - Catch research before it hits mainstream
  - url: https://arxiv.org/rss/cs.AI
    name: "arXiv Artificial Intelligence"
    tags: [AI, research, robotics, arxiv, frontier]
    enabled: true

  - url: https://arxiv.org/rss/cs.CV
    name: "arXiv Computer Vision"
    tags: [computer_vision, AI, robotics, research, arxiv, frontier]
    enabled: true

  - url: https://arxiv.org/rss/cs.LG
    name: "arXiv Machine Learning"
    tags: [machine_learning, AI, robotics, research, arxiv, frontier]
    enabled: true

  - url: https://arxiv.org/rss/stat.ML
    name: "arXiv Statistical ML"
    tags: [machine_learning, AI, robotics, research, arxiv, frontier]
    enabled: true

  - url: https://arxiv.org/rss/cs.RO
    name: "arXiv Robotics"
    tags: [robotics, research, arxiv, frontier]
    enabled: true

  # AI Research Newsletters & Aggregators
  - url: https://jack-clark.net/feed/
    name: "Import AI Newsletter"
    tags: [AI, robotics, research, frontier, newsletter]
    enabled: true

  - url: https://www.deeplearning.ai/thebatch/feed/
    name: "The Batch - DeepLearning.AI"
    tags: [AI, machine_learning, robotics, newsletter, research]
    enabled: true

  - url: https://paperswithcode.com/rss
    name: "Papers with Code"
    tags: [AI, machine_learning, robotics, open_source, research]
    enabled: true

  # 🧠 FRONTIER GITHUB REPOS
  - url: https://github.com/Kiloreux/awesome-robotics/commits/main.atom
    name: "Awesome Robotics Commits"
    tags: [robotics, open_source, research, github, frontier]
    enabled: true

  - url: https://github.com/josephmisiti/awesome-machine-learning/commits/master.atom
    name: "Awesome ML Commits"
    tags: [machine_learning, AI, open_source, github, frontier]
    enabled: true

  # 🧠 COMMUNITY & REAL-TIME SIGNALS
  # Hacker News RSS for real-time community signals
  - url: https://hnrss.org/newest?q=robotics
    name: "Hacker News Robotics"
    tags: [robotics, AI, hackernews, community, frontier]
    enabled: true

  - url: https://hnrss.org/newest?q=AI
    name: "Hacker News AI"
    tags: [AI, robotics, hackernews, community, frontier]
    enabled: true

  - url: https://hnrss.org/newest?q=machine+learning
    name: "Hacker News Machine Learning"
    tags: [machine_learning, AI, robotics, hackernews, community, frontier]
    enabled: true

  # Major AI Research Labs (WORKING)
  - url: https://www.microsoft.com/en-us/research/feed/
    name: "Microsoft Research"
    tags: [AI, robotics, microsoft, research, embodied_ai]
    enabled: true

  - url: https://deepmind.com/blog/feed/basic/
    name: "DeepMind Blog"
    tags: [AI, robotics, deepmind, research, embodied_ai]
    enabled: true

  - url: https://openai.com/blog/rss.xml
    name: "OpenAI Blog"
    tags: [AI, robotics, openai, research, embodied_ai]
    enabled: true

  # Academic & Research (WORKING)
  - url: https://www.science.org/action/showFeed?journalCode=scirobotics&type=etoc&feedType=rss
    name: "Science Robotics"
    tags: [robotics, research, science, academic]
    enabled: true

  - url: https://www.frontiersin.org/journals/robotics-and-ai/rss
    name: "Frontiers in Robotics & AI"
    tags: [robotics, research, academic, AI]
    enabled: true

  # Community (WORKING)
  - url: https://old.reddit.com/r/robotics/.rss
    name: "Reddit r/robotics"
    tags: [robotics, community, reddit]
    enabled: true

  - url: https://old.reddit.com/r/ROS/.rss
    name: "Reddit r/ROS"
    tags: [robotics, ros, community, reddit]
    enabled: true

  - url: https://old.reddit.com/r/AutonomousVehicles/.rss
    name: "Reddit r/AutonomousVehicles"
    tags: [robotics, autonomous_vehicles, community, reddit]
    enabled: true

  - url: https://old.reddit.com/r/drones/.rss
    name: "Reddit r/drones"
    tags: [robotics, drones, community, reddit]
    enabled: true

  - url: https://old.reddit.com/r/MachineLearning/.rss
    name: "Reddit r/MachineLearning"
    tags: [machine_learning, AI, robotics, community, reddit, frontier]
    enabled: true

  - url: https://old.reddit.com/r/artificial/.rss
    name: "Reddit r/artificial"
    tags: [AI, robotics, community, reddit, frontier]
    enabled: true

  # News & Industry (WORKING)
  - url: https://robohub.org/feed/
    name: "Robohub"
    tags: [robotics, news, research]
    enabled: true

  - url: https://roboticsandautomationnews.com/feed/
    name: "Robotics & Automation News"
    tags: [robotics, news, industry]
    enabled: true

# Filtering configuration
filters:
  # Keywords to include (content must contain at least one)
  include_keywords:
    # Core robotics terms
    - robotics
    - robot
    - autonomous
    - automation
    - AI
    - artificial intelligence
    - machine learning
    - computer vision
    - ROS
    - drone
    - self-driving
    - cobot
    - collaborative robot
    - autonomous vehicle
    - UAV
    - surgical robot
    - industrial robot
    - service robot
    - humanoid
    - swarm robotics
    - soft robotics
    - bio-inspired robotics
    - rehabilitation robot
    
    # 🧠 FRONTIER AI MODELS & CONCEPTS
    - VLA
    - V-JEPA
    - RT-2
    - SayCan
    - PaLM-E
    - GPT-5
    - multimodal transformer
    - foundation model
    - diffusion policy
    - hierarchical RL
    - world models
    - neural radiance fields
    - dreamerV3
    - embodied AI
    - vision-language-action
    - vision-language model
    - transformer-based control
    - reinforcement learning robotics
    - edge robotics
    - drone swarms
    - synthetic data robotics
    - robotics foundation models
    - sim-to-real
    - Policy Composition
    - Scene Graphs for Manipulation
    - robot foundation model
    - robot language model
    - robot vision model
    - robot learning model
    - robot reasoning
    - robot understanding
    - robot cognition
    - robot decision making
    - robot problem solving
    - robot adaptation
    - robot generalization
    - robot transfer learning
    - robot meta learning
    - robot few shot learning
    - robot zero shot learning
    - robot imitation learning
    - robot reinforcement learning
    - robot supervised learning
    - robot unsupervised learning
    - robot self supervised learning
    - robot multi task learning
    - robot continual learning
    - robot lifelong learning
    - robot online learning
    - robot active learning
    - robot curriculum learning
    - robot hierarchical learning
    - robot compositional learning
    - robot modular learning
    - robot distributed learning
    - robot federated learning
    - robot collaborative learning
    - robot swarm learning
    - robot collective learning
    - robot emergent behavior
    - robot self organization
    - robot self repair
    - robot self optimization
    - robot self adaptation
    - robot self improvement
    - robot self evolution

  # Keywords to exclude (content containing these will be filtered out)
  exclude_keywords:
    - job posting
    - hiring
    - career
    - webinar
    - advertisement
    - sponsored
    - sales pitch
    - apply now
    - remote work
    - internship
    - event registration
    - conference registration
    - workshop registration
    - training course
    - certification program
    # General science terms that don't indicate robotics
    - climate change
    - global warming
    - biodiversity
    - ecosystem
    - evolution
    - genetics
    - molecular biology
    - chemistry
    - physics
    - astronomy
    - astrophysics
    - geology
    - oceanography
    - meteorology
    - psychology
    - sociology
    - economics
    - political science
    - anthropology
    - archaeology
    - paleontology
    - microbiology
    - immunology
    - neurology
    - cardiology
    - oncology
    - epidemiology
    - public health
    - environmental science
    - conservation
    - sustainability

  # Minimum content length (characters)
  min_content_length: 100

  # Maximum age of posts (days)
  max_age_days: 7

# Scoring weights for RSS content
scoring_weights:
  # Base score for RSS content
  base_score: 50.0

  # Bonus for content length
  content_length_bonus: 0.1

  # Bonus for recent content (newer = higher score)
  recency_bonus: 10.0

  # Bonus for trusted sources
  source_bonus:
    arxiv: 30.0  # Highest bonus for research importance
    ieee: 15.0
    mit: 15.0
    science: 15.0
    robohub: 10.0
    nature: 18.0
    cell: 18.0
    pnas: 16.0
    nist: 12.0
    darpa: 12.0
    nasa: 12.0
    deepmind: 20.0
    openai: 18.0
    microsoft: 15.0
    # 🧠 FRONTIER SOURCES
    frontier: 35.0  # Highest bonus for frontier research
    hackernews: 8.0
    newsletter: 15.0
    github: 5.0

  # Bonus for specific tags
  tag_bonus:
    research: 5.0
    breakthrough: 10.0
    academic: 5.0
    technical: 3.0
    autonomous: 8.0
    medical: 7.0
    industrial: 4.0
    defense: 6.0
    space: 6.0
    embodied_ai: 12.0
    community: 2.0
    open_source: 3.0
    # 🧠 FRONTIER TAGS
    frontier: 20.0  # Highest bonus for frontier content
    arxiv: 10.0
    machine_learning: 8.0
    computer_vision: 8.0
    transformer: 10.0
    foundation_model: 15.0 