# Robotics Radar - Unified Feeds Configuration
# This file contains all feeds organized by profiles for easy switching

# Configuration profiles - set 'active_profile' to switch between them
active_profile: "frontier"  # Options: "frontier", "balanced", "industry", "clean"

profiles:
  frontier:
    name: "Frontier AI Research"
    description: "80% research, 20% industry - Catch breakthroughs 2-6 months early"
    feeds:
      # arXiv Research Feeds (Essential)
      - url: https://arxiv.org/rss/cs.AI
        name: "arXiv Artificial Intelligence"
        tags: [ai, research, robotics, arxiv]
        enabled: true

      - url: https://arxiv.org/rss/cs.CV
        name: "arXiv Computer Vision"
        tags: [computer vision, ai, robotics, research, arxiv]
        enabled: true

      - url: https://arxiv.org/rss/cs.LG
        name: "arXiv Machine Learning"
        tags: [machine learning, ai, robotics, research, arxiv]
        enabled: true

      - url: https://arxiv.org/rss/stat.ML
        name: "arXiv Statistical ML"
        tags: [machine learning, ai, robotics, research, arxiv]
        enabled: true

      - url: https://arxiv.org/rss/cs.RO
        name: "arXiv Robotics"
        tags: [robotics, research, arxiv, academic]
        enabled: true

      # AI Newsletters & Aggregators (High-Value)
      - url: https://jack-clark.net/feed/
        name: "Import AI Newsletter"
        tags: [ai, robotics, research, frontier, newsletter]
        enabled: true

      - url: https://www.deeplearning.ai/thebatch/feed/
        name: "The Batch - DeepLearning.AI"
        tags: [ai, machine learning, robotics, newsletter, research]
        enabled: true

      - url: https://paperswithcode.com/rss
        name: "Papers with Code"
        tags: [ai, machine learning, robotics, open-source, research]
        enabled: true

      # Frontier GitHub Repos (Real-Time ML research)
      - url: https://github.com/Kiloreux/awesome-robotics/commits/main.atom
        name: "Awesome Robotics Commits"
        tags: [robotics, open-source, research, github]
        enabled: true

      - url: https://github.com/josephmisiti/awesome-machine-learning/commits/master.atom
        name: "Awesome ML Commits"
        tags: [machine learning, ai, open-source, github]
        enabled: true

      # Community & Real-time signals
      - url: https://hnrss.org/newest?q=robotics
        name: "Hacker News Robotics"
        tags: [robotics, ai, hackernews, community]
        enabled: true

      - url: https://hnrss.org/newest?q=AI
        name: "Hacker News AI"
        tags: [ai, robotics, hackernews, community]
        enabled: true

      - url: https://www.reddit.com/r/MachineLearning/new.json
        name: "Reddit r/MachineLearning"
        tags: [machine learning, ai, robotics, reddit, community]
        enabled: true

      - url: https://www.reddit.com/r/artificial/new.json
        name: "Reddit r/artificial"
        tags: [ai, robotics, reddit, community]
        enabled: true

      # Core Robotics Sources
      - url: https://robohub.org/feed/
        name: "Robohub"
        tags: [robotics, research, academic]
        enabled: true

      - url: https://www.science.org/action/showFeed?journalCode=scirobotics&type=etoc&feedType=rss
        name: "Science Robotics"
        tags: [science, research, robotics]
        enabled: true

      - url: https://www.frontiersin.org/journals/robotics-and-ai/rss
        name: "Frontiers in Robotics & AI"
        tags: [robotics, research, academic]
        enabled: true

      # Weekly Robotics Curated Sources (High-Quality)
      - url: https://eurobot.org/feed
        name: "Eurobot"
        tags: [robotics, competition, europe, weekly-robotics]
        enabled: true

      - url: https://events.linuxfoundation.org/feed
        name: "Linux Foundation Events"
        tags: [robotics, open-source, events, weekly-robotics]
        enabled: true

      - url: https://hackaday.com/feed
        name: "Hackaday"
        tags: [robotics, hardware, diy, weekly-robotics]
        enabled: true

      - url: https://spectrum.ieee.org/rss
        name: "IEEE Spectrum"
        tags: [robotics, technology, ieee, weekly-robotics]
        enabled: true

      - url: https://2024.oshwa.org/feed
        name: "OSHWA 2024"
        tags: [robotics, open-hardware, weekly-robotics]
        enabled: true

      - url: https://roboticsconference.org/atom
        name: "Robotics Conference"
        tags: [robotics, conference, research, weekly-robotics]
        enabled: true

      - url: https://cppcon.org/feed
        name: "CppCon"
        tags: [robotics, programming, cpp, weekly-robotics]
        enabled: true

      - url: https://2025.robocup.org/feed
        name: "RoboCup 2025"
        tags: [robotics, competition, ai, weekly-robotics]
        enabled: true

      # Industry & News Sources
      - url: https://www.therobotreport.com/feed/
        name: "The Robot Report"
        tags: [robotics, news, industry]
        enabled: true

      - url: https://roboticsandautomationnews.com/feed/
        name: "Robotics & Automation News"
        tags: [robotics, news, industry]
        enabled: true

      # AI Company Blogs
      - url: https://blog.deepmind.com/feed/brand/deepmind/
        name: "DeepMind Blog"
        tags: [ai, robotics, research, deepmind]
        enabled: true

      - url: https://openai.com/blog/rss.xml
        name: "OpenAI Blog"
        tags: [ai, robotics, research, openai]
        enabled: true

      - url: https://research.microsoft.com/en-us/rss/
        name: "Microsoft Research"
        tags: [ai, robotics, research, microsoft]
        enabled: true

  balanced:
    name: "Balanced Coverage"
    description: "50% research, 50% industry - Good mix for professionals"
    feeds:
      # Core Robotics Sources
      - url: https://robohub.org/feed/
        name: "Robohub"
        tags: [robotics, research, academic]
        enabled: true

      - url: https://www.therobotreport.com/feed/
        name: "The Robot Report"
        tags: [robotics, news, industry]
        enabled: true

      - url: https://roboticsandautomationnews.com/feed/
        name: "Robotics & Automation News"
        tags: [robotics, news, industry]
        enabled: true

      - url: https://spectrum.ieee.org/robotics/rss.xml
        name: "IEEE Spectrum Robotics"
        tags: [robotics, engineering, technical]
        enabled: true

      # Research Sources
      - url: https://arxiv.org/rss/cs.RO
        name: "arXiv Robotics"
        tags: [robotics, research, arxiv, academic]
        enabled: true

      - url: https://www.science.org/action/showFeed?journalCode=scirobotics&type=etoc&feedType=rss
        name: "Science Robotics"
        tags: [science, research, robotics]
        enabled: true

      # Community Sources
      - url: https://www.reddit.com/r/robotics/new.json
        name: "Reddit r/robotics"
        tags: [robotics, reddit, community]
        enabled: true

      - url: https://hnrss.org/newest?q=robotics
        name: "Hacker News Robotics"
        tags: [robotics, ai, hackernews, community]
        enabled: true

  industry:
    name: "Industry Focus"
    description: "20% research, 80% industry - Business applications"
    feeds:
      # Industry News
      - url: https://www.roboticsbusinessreview.com/feed/
        name: "Robotics Business Review"
        tags: [robotics, news, business]
        enabled: true

      - url: https://www.therobotreport.com/feed/
        name: "The Robot Report"
        tags: [robotics, news, industry]
        enabled: true

      - url: https://roboticsandautomationnews.com/feed/
        name: "Robotics & Automation News"
        tags: [robotics, news, industry]
        enabled: true

      - url: https://spectrum.ieee.org/robotics/rss.xml
        name: "IEEE Spectrum Robotics"
        tags: [robotics, engineering, technical]
        enabled: true

      # Company Blogs
      - url: https://blog.deepmind.com/feed/brand/deepmind/
        name: "DeepMind Blog"
        tags: [ai, robotics, research, deepmind]
        enabled: true

      - url: https://openai.com/blog/rss.xml
        name: "OpenAI Blog"
        tags: [ai, robotics, research, openai]
        enabled: true

  clean:
    name: "Clean & Validated"
    description: "Only feeds that pass validation tests"
    feeds:
      # Validated feeds only
      - url: https://robohub.org/feed/
        name: "Robohub"
        tags: [robotics, research, academic]
        enabled: true

      - url: https://roboticsandautomationnews.com/feed/
        name: "Robotics & Automation News"
        tags: [robotics, news, industry]
        enabled: true

      - url: https://www.theguardian.com/technology/robots/rss
        name: "The Guardian - Robots"
        tags: [robotics, news, general]
        enabled: true

      - url: https://www.science.org/action/showFeed?journalCode=scirobotics&type=etoc&feedType=rss
        name: "Science Robotics"
        tags: [science, research, robotics]
        enabled: true

      - url: https://www.frontiersin.org/journals/robotics-and-ai/rss
        name: "Frontiers in Robotics & AI"
        tags: [robotics, research, academic]
        enabled: true

      - url: https://www.sciencedaily.com/rss/computers_math/robotics.xml
        name: "ScienceDaily Robotics"
        tags: [robotics, science, news]
        enabled: true

      - url: https://github.com/ros/rosdistro/commits/master.atom
        name: "ROS Distro Commits"
        tags: [robotics, open-source, ros, github]
        enabled: true

      - url: https://research.microsoft.com/en-us/rss/
        name: "Microsoft Research"
        tags: [ai, robotics, research, microsoft]
        enabled: true

      - url: https://blog.deepmind.com/feed/brand/deepmind/
        name: "DeepMind Blog"
        tags: [ai, robotics, research, deepmind]
        enabled: true

      - url: https://openai.com/blog/rss.xml
        name: "OpenAI Blog"
        tags: [ai, robotics, research, openai]
        enabled: true

      - url: https://www.reddit.com/r/robotics/new.json
        name: "Reddit r/robotics"
        tags: [robotics, reddit, community]
        enabled: true

      - url: https://www.reddit.com/r/ROS/new.json
        name: "Reddit r/ROS"
        tags: [robotics, ros, reddit, community]
        enabled: true

      - url: https://www.reddit.com/r/AutonomousVehicles/new.json
        name: "Reddit r/AutonomousVehicles"
        tags: [autonomous vehicles, robotics, reddit, community]
        enabled: true

      - url: https://www.reddit.com/r/drones/new.json
        name: "Reddit r/drones"
        tags: [drones, robotics, reddit, community]
        enabled: true

      - url: https://medium.com/feed/tag/robotics
        name: "Medium Robotics"
        tags: [robotics, medium, community]
        enabled: true

      - url: https://www.nasa.gov/feed/
        name: "NASA News"
        tags: [space, robotics, nasa, research]
        enabled: true

# Scoring weights for different source types
scoring_weights:
  source_bonus:
    arxiv: 30.0
    frontier: 35.0
    newsletter: 25.0
    hackernews: 20.0
    twitter: 15.0
    github: 18.0
    machine_learning: 22.0
    computer_vision: 20.0
    transformer: 25.0
    foundation_model: 30.0
    research: 20.0
    academic: 18.0
    industry: 15.0
    news: 12.0
    community: 10.0

  tag_bonus:
    arxiv: 25.0
    frontier: 30.0
    newsletter: 20.0
    hackernews: 15.0
    twitter: 12.0
    github: 15.0
    machine_learning: 18.0
    computer_vision: 16.0
    transformer: 20.0
    foundation_model: 25.0
    research: 15.0
    academic: 14.0
    industry: 12.0
    news: 10.0
    community: 8.0

# Filtering configuration
filtering:
  min_score_threshold: 10.0
  max_articles_per_source: 100
  fetch_interval_seconds: 10 