domain: robotics
keywords:
  # Core robotics terms
  - robotics research
  - open-source robotics
  - robot announcement
  - autonomous systems
  - AI robotics
  - robotic arm
  - computer vision robotics
  - ROS2
  - industrial robotics
  - service robots
  - drone technology
  - self-driving cars
  - robotic surgery
  - humanoid robots
  - swarm robotics
  - soft robotics
  - bio-inspired robotics
  - collaborative robots
  - mobile robotics
  - robotic learning
  - Vision-Language-Action (VLA)
  - vision-language models
  - V-JEPA 2
  - transformer-based control
  - reinforcement learning robotics
  - diffusion policy
  - edge robotics
  - drone swarms
  - embodied AI
  - synthetic data robotics
  - robotics foundation models
  - sim-to-real
  - Policy Composition
  - Hierarchical RL
  - Scene Graphs for Manipulation
  
  # Additional specific robotics terms
  - robot
  - robotics
  - autonomous robot
  - robot control
  - robot navigation
  - robot manipulation
  - robot perception
  - robot planning
  - robot learning
  - robot vision
  - robot sensing
  - robot actuation
  - robot locomotion
  - robot interaction
  - robot collaboration
  - robot safety
  - robot ethics
  - robot autonomy
  - robot intelligence
  - robot adaptation
  - robot optimization
  - robot simulation
  - robot hardware
  - robot software
  - robot platform
  - robot system
  - robot application
  - robot deployment
  - robot testing
  - robot validation
  
  # Synonyms and alternative terms
  - driverless
  - cobot
  - collaborative robot
  - mobile manipulator
  - assistive robot
  - factory automation
  - machine autonomy
  - automated system
  - intelligent machine
  - smart robot
  - robotic system
  - automation technology
  - robotic automation
  - autonomous system
  - robotic platform
  - robotic solution
  - robotic application
  - robotic technology
  - robotic innovation
  - robotic development
  - robotic research
  - robotic engineering
  - robotic design
  - robotic implementation
  - robotic deployment
  - robotic integration
  - robotic optimization
  - robotic control
  - robotic navigation
  - robotic perception
  - robotic planning
  - robotic learning
  - robotic vision
  - robotic sensing
  - robotic actuation
  - robotic locomotion
  - robotic interaction
  - robotic collaboration
  - robotic safety
  - robotic ethics
  - robotic autonomy
  - robotic intelligence
  - robotic adaptation
  - robotic simulation
  - robotic hardware
  - robotic software
  - robotic testing
  - robotic validation
  
  # AI for Robotics trends and models
  - foundation model
  - VLA
  - Vision-Language-Action
  - RT-2
  - V-JEPA
  - Diffusion Policy
  - PaLM-E
  - SayCan
  - embodied AI
  - embodied intelligence
  - robot foundation model
  - robot language model
  - robot vision model
  - robot learning model
  - robot reasoning
  - robot understanding
  - robot cognition
  - robot decision making
  - robot problem solving
  - robot adaptation
  - robot generalization
  - robot transfer learning
  - robot meta learning
  - robot few shot learning
  - robot zero shot learning
  - robot imitation learning
  - robot reinforcement learning
  - robot supervised learning
  - robot unsupervised learning
  - robot self supervised learning
  - robot multi task learning
  - robot continual learning
  - robot lifelong learning
  - robot online learning
  - robot active learning
  - robot curriculum learning
  - robot hierarchical learning
  - robot compositional learning
  - robot modular learning
  - robot distributed learning
  - robot federated learning
  - robot collaborative learning
  - robot swarm learning
  - robot collective learning
  - robot emergent behavior
  - robot self organization
  - robot self repair
  - robot self optimization
  - robot self adaptation
  - robot self improvement
  - robot self evolution
languages:
  - en
exclude_keywords:
  - hiring
  - webinar
  - job posting
  - career
  - apply now
  - remote work
  - internship
  - sales pitch
  - advertisement
  - sponsored
  # General science terms that don't indicate robotics
  - climate change
  - global warming
  - biodiversity
  - ecosystem
  - evolution
  - genetics
  - molecular biology
  - chemistry
  - physics
  - astronomy
  - astrophysics
  - geology
  - oceanography
  - meteorology
  - psychology
  - sociology
  - economics
  - political science
  - anthropology
  - archaeology
  - paleontology
  - microbiology
  - immunology
  - neurology
  - cardiology
  - oncology
  - epidemiology
  - public health
  - environmental science
  - conservation
  - sustainability

# Scoring configuration
scoring_weights:
  likes: 1.0
  retweets: 2.0
  replies: 1.5
  user_feedback: 3.0
  author_followers: 0.1
  content_length: 0.5

# Category-based scoring weights
category_weights:
  industrial_automation: 1.0
  educational_robotics: 1.0
  robotics_ethics: 0.5
  agricultural_robotics: 10.0
  medical_robotics: 1.0
  autonomous_vehicles: 10.0
  humanoid_robotics: 8.0
  swarm_robotics: 5.0
  soft_robotics: 0.5
  research_robotics: 1.0
  consumer_robotics: 1.0
  military_robotics: 1.0
  space_robotics: 1.0
  underwater_robotics: 1.0
  aerial_robotics: 1.0
  collaborative_robotics: 1.0
  mobile_robotics: 1.0
  robotics_software: 1.0
  robotics_hardware: 1.0
  ai_robotics: 1.0
  robotics_general: 0.5  # Default weight for general robotics content

# User preference learning
user_preferences:
  enabled: true
  learning_rate: 0.1
  decay_factor: 0.95
  min_feedback_count: 3

# Filtering thresholds
min_likes: 10
min_retweets: 5
min_author_followers: 1000

# Notification settings
top_tweets_count: 10
notification_frequency: "10s"  # (For production, use "2h" instead of 10s)